### ISSUE TITLE
Create a DNS record for staging.otako.moe

### ISSUE THREAD

**Issue by binn** [KibiiTV/otako.moe#14]
Simple to-do for me lol.

All we need to do is create the record, move the record for `otako.moe` somewhere else and prepare for this.

I'm excited about when the documentation and hyped for release.

**Comment by binn** [comment]
Also can't forget, change the CNAME file in here to also account for it!

**Comment by Greek** [comment]
k

**Comment by binn** [comment]
Right, this is done, all that's left is throw in the CNAME commit and link this issue; then close!

**Comment by binn** [comment]
Finished.
