### ISSUE TITLE
OI MATE CAN SOMEONE TELL PIXL THAT MY ACCOUNT IS LOCKED AND TO CHECK HER DAMN EMAIL

### ISSUE THREAD

**Issue by binn** [KibiiTV/otako.moe#16]
FUCKING I GOT LOCKED AND I NEED A NUMBER TO USE REEE

**Comment by binn** [comment]
HELPPPPPPPPPPPP

**Comment by binn** [comment]
GITHUB WEBHOOKS TO THE RESCUE AMIRITE

**Comment by binn** [comment]
SOMEONE PASTE THIS LINK IN CHAT http://pixel.is-my.world/rpgrxd.png
AAAAAAAAAAAAAa

**Comment by binn** [comment]
IS ANYONE EVEN THERE

**Comment by binn** [comment]
HECC

**Comment by binn** [comment]
ok thanks github http://pixel.is-my.world/hjcglh.png

**Comment by binn** [comment]
@apap04 @PryDt @YazawaNic0 SOMEONE HELP ME

**Comment by binn** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEE Y U DO THIS TO ME

**Comment by prydt** [comment]
sure

**Comment by binn** [comment]
WHERE THE FUCK. ACTUAL FUCK. IS EVERYONE

**Comment by binn** [comment]
ok prydt hi

**Comment by binn** [comment]
i need help prydt im locked out

**Comment by binn** [comment]
from discord

**Comment by prydt** [comment]
Soo, what do I do?

**Comment by binn** [comment]
idk but i need a number http://pixel.is-my.world/kwgqjj.png

**Comment by binn** [comment]
![http://pixel.is-my.world/kwgqjj.png]

**Comment by binn** [comment]
wait

**Comment by binn** [comment]
wait fuk ![](http://pixel.is-my.world/kwgqjj.png)

**Comment by prydt** [comment]
Kk

**Comment by MageLegend** [comment]
rip

**Comment by binn** [comment]
hELP

**Comment by MageLegend** [comment]
yea we pinged pixel

**Comment by binn** [comment]
can sum1 dm her or some shit

**Comment by binn** [comment]
tfw she isn't responding on texts or whatsapp

**Comment by binn** [comment]
o shet it's 11pm she might be asleep

**Comment by MageLegend** [comment]
yea maybe

**Comment by binn** [comment]
hECCCCCC

**Comment by JulSantos** [comment]
She is in the voicechat tho

**Comment by 0x21F** [comment]
oof

**Comment by MageLegend** [comment]
she has her mic muted so prob afk

**Comment by JulSantos** [comment]
Maybe

**Comment by 0x21F** [comment]
I would think so

**Comment by JulSantos** [comment]
But bin do you need an email to use or something?

**Comment by 0x21F** [comment]
he needs a phone number

**Comment by 0x21F** [comment]
oof

**Comment by binn** [comment]
no i need a number

**Comment by binn** [comment]
kms

**Comment by JulSantos** [comment]
Bin I could give you my number but my phone is out of battery feelsuselessgril

**Comment by JulSantos** [comment]
It says you're online in discord tho

**Comment by binn** [comment]
rip

**Comment by binn** [comment]
o im online cos discord client is still open

**Comment by JulSantos** [comment]
Gotcha

**Comment by binn** [comment]
i can selfbot in still just i cant access discord via client

**Comment by 0x21F** [comment]
oof

**Comment by JulSantos** [comment]
But don't you have a phone number or something?

**Comment by 0x21F** [comment]
It was wet down south

**Comment by binn** [comment]
no lol

**Comment by binn** [comment]
i'm stuck REEE

**Comment by binn** [comment]
someone talk to me ffs

**Comment by Greek** [comment]
use irc

**Comment by MageLegend** [comment]
ye

**Comment by binn** [comment]
no

**Comment by binn** [comment]
saving this here ![](http://pixel.is-my.world/umilfp.png)

**Comment by JulSantos** [comment]
Kk bin pixl won't answer us

**Comment by binn** [comment]
ya she's prob asleept

**Comment by binn** [comment]
rip

**Comment by binn** [comment]
well i got my friend's number but it's invalid for some reason

**Comment by binn** [comment]
hot stuff discord :ok_hand:

**Comment by Greek** [comment]
nc i cei cieic eiiciecieicie

**Comment by binn** [comment]
damn it

**Comment by prydt** [comment]
@bin http://harmful.cat-v.org/software/java read this

**Comment by binn** [comment]
apap do u have a number

**Comment by Greek** [comment]
y e s

**Comment by binn** [comment]
nice meme

**Comment by binn** [comment]
can i use it

**Comment by Greek** [comment]
it is
443-666-6666

**Comment by JulSantos** [comment]
bin I don't think you can use my number.. I'm portuguese I thing the number format is diffrent idk

**Comment by Greek** [comment]
n a ah h h h h h h h hh  h 
use it
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Greek** [comment]
hh

**Comment by JulSantos** [comment]
It probably won't work Idk

**Comment by binn** [comment]
nah i'll use apap's jul

**Comment by binn** [comment]
if he actually has one that isn't 666

**Comment by JulSantos** [comment]
Yeah lmao

**Comment by Greek** [comment]
try pizzza huts

hehe

**Comment by binn** [comment]
ok kys

**Comment by JulSantos** [comment]
apap I don't think he is joking about it tbh.... Be serious please?

**Comment by Greek** [comment]
lets use linux's method 
where people email us for paches

**Comment by JulSantos** [comment]
Bruh

**Comment by Greek** [comment]
i dun wanna giv my phone number
nya

**Comment by JulSantos** [comment]
bin I'll keep spamming pixl then

**Comment by JulSantos** [comment]
She just won't answer

**Comment by JulSantos** [comment]
bin can you use numbers with this format?: Ex: 961820982

**Comment by Greek** [comment]
N O

**Comment by Greek** [comment]
i cant

**Comment by Greek** [comment]
![image](https://user-images.githubusercontent.com/17275723/33745056-a48405ee-db82-11e7-9d94-ef9535087423.png)

**Comment by JulSantos** [comment]
m8 
stawp

**Comment by binn** [comment]
i can but i'd prefer to use the number of a friend ik xd

**Comment by binn** [comment]
apap email me ur number

**Comment by Greek** [comment]
inspect element it

**Comment by binn** [comment]
to alltrashybin@gmail.com

**Comment by Greek** [comment]
![image](https://user-images.githubusercontent.com/17275723/33745089-deb2dc7c-db82-11e7-9555-4839db40da90.png)

**Comment by binn** [comment]
ok can u give me ur number pixel isn't responding

**Comment by Greek** [comment]
nu
i dont wanna

**Comment by binn** [comment]
yes u do

**Comment by Greek** [comment]
cuz my parents
ree

**Comment by binn** [comment]
they wont know hurry up

**Comment by JulSantos** [comment]
Ye bin understandable

**Comment by binn** [comment]
its legit one thing smh

**Comment by JulSantos** [comment]
bin can't you just use a diffrent account?

**Comment by binn** [comment]
i can but fuck that

**Comment by JulSantos** [comment]
Kk lmao

**Comment by Greek** [comment]
no cuz its gon be gay again
awaaaaaaaaaaaaaaaaaaaaaa

**Comment by JulSantos** [comment]
bin do you want a number or what

**Comment by Greek** [comment]
whats up with ur current one

**Comment by binn** [comment]
i DO BUT REEE

**Comment by JulSantos** [comment]
lmao

**Comment by binn** [comment]
ok help

**Comment by JulSantos** [comment]
I'm spamming 4 help

**Comment by JulSantos** [comment]
![unknown](https://user-images.githubusercontent.com/34355730/33745277-ba338d62-dbad-11e7-8334-3eac0db23893.png)

**Comment by MageLegend** [comment]
A

**Comment by MageLegend** [comment]
Need mine?

**Comment by Greek** [comment]
EYS
YES

**Comment by Greek** [comment]
PLS

**Comment by Greek** [comment]
WE NEED BIN BACK

**Comment by JulSantos** [comment]
Mage took so long to offer his phone number lmfaooo

**Comment by Greek** [comment]
dont speak too soon

**Comment by MageLegend** [comment]
It's already linked to my account though so idk if it'll work

**Comment by Greek** [comment]
FCUC

**Comment by Missingno74** [comment]
neat

**Comment by MageLegend** [comment]
Jul stop sucking dick

**Comment by Greek** [comment]
nic epfp

**Comment by Missingno74** [comment]
ok

**Comment by JulSantos** [comment]
Why are you saying that Mage

**Comment by binn** [comment]
ok so just
email it to my place

**Comment by JulSantos** [comment]
mMmMmMmMm

**Comment by binn** [comment]
omae wa mou shindeiru

**Comment by Greek** [comment]
no u

**Comment by binn** [comment]
おまえわもうしんでいる

**Comment by JulSantos** [comment]
<img width="254" alt="busted waffles" src="https://user-images.githubusercontent.com/34355730/33745335-36ada59e-dbae-11e7-896b-b1a7c22ee827.png">

**Comment by binn** [comment]
see that's pixl right there

**Comment by Missingno74** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Greek** [comment]
EYS

**Comment by JulSantos** [comment]
Were bin

**Comment by JulSantos** [comment]
feelsconfusedgril

**Comment by JulSantos** [comment]
pixl is making babies

**Comment by binn** [comment]
xd

**Comment by JulSantos** [comment]
nice

**Comment by JulSantos** [comment]
nice

**Comment by Greek** [comment]
https://puu.sh/yBDvo/86dda913fa.png

**Comment by Greek** [comment]
![image](https://user-images.githubusercontent.com/17275723/33745378-901224cc-db84-11e7-85ae-13425ab0645d.png)

**Comment by binn** [comment]
with me yes

**Comment by binn** [comment]
@MageLegend can u email me ur number pls

**Comment by binn** [comment]
and country code

**Comment by JulSantos** [comment]
bin does pixl get afk so often feelsthinkinggril

**Comment by MageLegend** [comment]
What's your email again

**Comment by MarshadowBoi** [comment]
beep

**Comment by MageLegend** [comment]
Nvm got it

**Comment by MarshadowBoi** [comment]
bepis sipeb
sipleb

**Comment by MarshadowBoi** [comment]
BEEP BEEP

**Comment by binn** [comment]
is u send it

**Comment by binn** [comment]
did*

**Comment by MageLegend** [comment]
Ye

**Comment by binn** [comment]
is ur country code correct

**Comment by binn** [comment]
+32 or +31 (you sent me +32)

**Comment by MageLegend** [comment]
Yea

**Comment by binn** [comment]
@MageLegend

**Comment by binn** [comment]
ok

**Comment by MageLegend** [comment]
It might not work cause it's already linked to my account

**Comment by binn** [comment]
oi tell me the 6 digit code

**Comment by MageLegend** [comment]
Check your email

**Comment by zaida04** [comment]
bin. lol why didnt you just call me, i would have given you my moms number i had her phone lol

**Comment by zaida04** [comment]
also i wish pings on github worked like in discord
